name: "\U0001F41E Report a problem"
description: "Report an issue with `ggg`"
title: "Bug: (fill in)"
labels:
  - bug
  - "repro:needed"
body:

  - type: dropdown
    attributes:
      label: Version
      description: Please tell us which version of `ggg` are you running (Run `ggg --version`.)
      multiple: false
      options:
        - 0.0.1
        - 1.0.0 (Edge)
        - From some commit (provide commit hash in additional comments below)
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: |
        You can use Markdown in this field.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What actually happened?
      description: |
        Please copy-paste the actual output (If you can, run `ggg` with `--debug` flag for more details).
        You can use Markdown in this field.
      value: |
        <details>
        <summary>Output</summary>

        ```
        <!-- Paste your output here -->
        ```
        </details>
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false

  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important to know?
