name: "\U0001F4DD Request a new feature"
description: "Request a new feature"
title: "Feture Request: (fill in)"
labels:
  - enhancement
body:

  - type: dropdown
    attributes:
      label: Version
      description: Please tell us which version are you currently using (Run `ggg --version`.)
      multiple: false
      options:
        - 0.0.1
        - 1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: What problem do you want to solve?
      description: |
        Please explain your use case in as much detail as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What do you think is the correct solution?
      description: |
        Please explain how you'd like to change ggg to address the problem.

  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false

  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important to know?
